package edu.uga.cs.project4v1;

import androidx.appcompat.app.AppCompatActivity;

import android.content.ContentValues;
import android.content.Intent;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.opencsv.CSVReader;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.List;

public class MainActivity extends AppCompatActivity {


    private TextView text;
    private Button quiz;
    private Button results;
    private Button help;
    private quizData quizdata = null;
    private static SQLiteDatabase db;

    /**
     * this is what creates the activity
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        quizdata = new quizData(this);

        /**
         *buttons becoming initialized
         */

        text = findViewById(R.id.textView);
        quiz = findViewById(R.id.startQuiz);
        results = findViewById(R.id.showResults);
        help = findViewById(R.id.help);





        quiz.setOnClickListener( new quizButtonClickListener() );
        results.setOnClickListener( new resultsButtonClickListener() );
        help.setOnClickListener( new helpButtonClickListener() );

    }

    /**
     * this method lets stuff happen in the
     * background while the app is in onResume
     */

    protected void onResume(){
        super.onResume();


        quizdata.open();
        List<QuizResult> list = quizData.retrieveAllQuizzes();

        if(list.size() == 0) {
            createDb();

        }







    }

    /**
     * this method writes data into our database
     *
     */

    public void createDb(){

        try {
            // Open the CSV data file in the assets folder
            InputStream in_s = getAssets().open( "state_capitals.csv" );
            // get the TableLayout view
            // read the CSV data
            CSVReader reader = new CSVReader( new InputStreamReader( in_s ) );
            String[] nextLine;
            while( ( nextLine = reader.readNext() ) != null ) {
                // nextLine[] is an array of values from the line
                // create the next table row for the layout
                //for( int i = 0; i < nextLine.length; i++ ) {

                questions question = new questions(nextLine[0],nextLine[1],nextLine[2],nextLine[3]);

                // Prepare the values for all of the necessary columns in the table
                // and set their values to the variables of the JobLead argument.
                // This is how we are providing persistence to a JobLead (Java object) instance
                // by storing it as a new row in the database table representing job leads.
                ContentValues values = new ContentValues();

                values.put( DBhelper.QUESTIONS_STATE_NAME, question.getStateName() );
                values.put( DBhelper.QUESTIONS_CAPITAL, question.getCapital() );
                values.put( DBhelper.QUESTIONS_ALT_ONE, question.getaltOne() );
                values.put( DBhelper.QUESTIONS_ALT_TWO, question.getaltTwo() );
                // Insert the new row into the database table;
                // The id (primary key) is automatically generated by the database system
                // and returned as from the insert method call.
                long id = db.insert( DBhelper.TABLE_QUESTIONS, null, values );

                // store the id (the primary key) in the JobLead instance, as it is now persistent
                question.setId( id );

                //Log.d( DEBUG_TAG, "Stored new job lead with id: " + String.valueOf( question.getId() ) );


            }


        } catch (Exception e) {
            //Log.e( TAG, e.toString() );
        }
    }






    private class quizButtonClickListener implements View.OnClickListener
    {

        @Override
        public void onClick(View v) {

            Intent intent = new Intent(v.getContext(), startQuiz.class);

            v.getContext().startActivity(intent);

        }
    }


    /**
     * Button click listener for the overview button
     *
     *
     *
     *
     */
    private class resultsButtonClickListener implements View.OnClickListener
    {

        @Override
        public void onClick(View v) {

            Intent intent = new Intent(v.getContext(), PastQuizzes.class);

            v.getContext().startActivity(intent);

        }
    }


    /**
     * Button click listener for the overview button
     *
     *
     *
     *
     */
    private class helpButtonClickListener implements View.OnClickListener
    {

        @Override
        public void onClick(View v) {

            Intent intent = new Intent(v.getContext(), Help.class);
            v.getContext().startActivity(intent);

        }
    }









}